let settings = {
  title: "Smart Citizen",
  logo: "logo-sc.svg",
  filter: {type: "", value: "" },
  searchBar: true,
  primarySensor: { id: 56, threshold: [75, 85] },
  // sensors: [
  //   {id: 10, threshold: [75, 85] },
  //   {id: 5, threshold: [75, 85] },
  //   {id: 4, threshold: [75, 85] },
  //   {id: 8, threshold: [75, 85] },
  //   {id: 9, threshold: [75, 85] },
  //   {id: 21, threshold: [75, 85] },
  //   {id: 7, threshold: [75, 85] },
  //   {id: 6, threshold: [25, 45] },
  // ],
  indexView: ["user", "city", "tags", "id"],
  styles: {
    colorBase: "#151515",
    colorBody: "#FFFFFF",
    colorBackground: "#e0e8ea",
    colorTrue: "#349353",
    colorFalse: "#e74c3d",
  },
};