let settings = {
  title: "Smart Citizen",
  logo: "logo-sc.svg",
  filter: {type: "", value: "" },
  searchBar: true,
  primarySensor: { id: 56, threshold: [75, 85] },
  // sensors: [
  //   {id: 10, threshold: [75, 85] },
  //   {id: 5, threshold: [75, 85] },
  //   {id: 4, threshold: [75, 85] },
  //   {id: 8, threshold: [75, 85] },
  //   {id: 9, threshold: [75, 85] },
  //   {id: 21, threshold: [75, 85] },
  //   {id: 7, threshold: [75, 85] },
  //   {id: 6, threshold: [25, 45] },
  // ],
  indexView: ["user", "city", "tags", "id"],
  styles: {
    colorBase: "#2e2e2e",
    colorBody: "#FFFFFF",
    colorBackground: "#ebebed",
    colorTrue: "#019b33",
    colorFalse: "#ff2626",
    borderWidth: "2px",
    borderRadius: "4px",
  },
};

// let settings = {
//   title: "Barcelona's humidity",
//   // logo: "logo-sc.svg",
//   filter: {type: "city", value: "Barcelona" },
//   searchBar: false,
//   primarySensor: { id: 56, threshold: [75, 85] },
//   // sensors: [
//   //   {id: 10, threshold: [75, 85] },
//   //   {id: 5, threshold: [75, 85] },
//   //   {id: 4, threshold: [75, 85] },
//   //   {id: 8, threshold: [75, 85] },
//   //   {id: 9, threshold: [75, 85] },
//   //   {id: 21, threshold: [75, 85] },
//   //   {id: 7, threshold: [75, 85] },
//   //   {id: 6, threshold: [25, 45] },
//   // ],
//   indexView: [],
//   styles: {
//     colorBase: "#0b0b0b",
//     colorBody: "#fffdf4",
//     colorBackground: "#fffdf4",
//     colorTrue: "#66b963",
//     colorFalse: "#f96341",
//     borderWidth: "1px",
//     borderRadius: "50%",
//   },
//   minimalistic: true,
// };